// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto.proto

/*
Package crypto is a generated protocol buffer package.

It is generated from these files:
	crypto.proto

It has these top-level messages:
	Digest256
*/
package crypto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Digest256 struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Digest256) Reset()                    { *m = Digest256{} }
func (m *Digest256) String() string            { return proto.CompactTextString(m) }
func (*Digest256) ProtoMessage()               {}
func (*Digest256) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Digest256) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Digest256)(nil), "crypto.Digest256")
}

func init() { proto.RegisterFile("crypto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xe4, 0xb9, 0x38,
	0x5d, 0x32, 0xd3, 0x53, 0x8b, 0x4b, 0x8c, 0x4c, 0xcd, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b,
	0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x7a, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x14, 0x0d, 0x0f, 0x3f, 0x00, 0x00, 0x00,
}
